name: Setup Workspace
description: Sets up the Rust workspace, installs toolchain, and checks dependencies

runs:
  using: composite
  steps:
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache Cargo Registry and Build
      uses: Swatinem/rust-cache@v2

    - name: Check Formatting
      shell: bash
      run: cargo fmt --all -- --check

    - name: Check Clippy (Linting)
      shell: bash
      run: cargo clippy -- -D warnings

    - name: Check Dependencies
      shell: bash
      run: cargo check
