name: Build and Push Docker Image
description: Builds a Docker image and pushes it to a registry (supports multi-arch)

inputs:
  registry:
    description: Container registry (e.g., ghcr.io)
    required: true
    default: ghcr.io
  image_name:
    description: Image name (e.g., owner/repo)
    required: true
  username:
    description: Registry username
    required: true
  password:
    description: Registry password
    required: true
  platforms:
    description: Target platforms (comma separated)
    default: linux/arm64

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=latest
          type=sha,format=long

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
