name: Setup OCI Credentials
description: Configures OCI credentials and environment variables for Terraform

inputs:
  oci_private_key:
    description: "OCI Private Key content"
    required: true
  oci_tenancy_ocid:
    description: "OCI Tenancy OCID"
    required: true
  oci_user_ocid:
    description: "OCI User OCID"
    required: true
  oci_fingerprint:
    description: "OCI Fingerprint"
    required: true
  oci_region:
    description: "OCI Region"
    required: true
  ssh_public_key:
    description: "SSH Public Key"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup OCI Config and Environment
      shell: bash
      run: |
        # 1. Create the Private Key File
        mkdir -p $HOME/.oci
        echo "${{ inputs.oci_private_key }}" > $HOME/.oci/oci_api_key.pem
        chmod 600 $HOME/.oci/oci_api_key.pem

        # 2. Create the OCI Config File (Standard format for Backend Auth)
        cat <<EOF > $HOME/.oci/config
        [DEFAULT]
        user=${{ inputs.oci_user_ocid }}
        fingerprint=${{ inputs.oci_fingerprint }}
        tenancy=${{ inputs.oci_tenancy_ocid }}
        region=${{ inputs.oci_region }}
        key_file=$HOME/.oci/oci_api_key.pem
        EOF
        chmod 600 $HOME/.oci/config

        # 3. Set Environment Variables

        # Point Terraform Backend to the config file
        echo "OCI_CLI_CONFIG_FILE=$HOME/.oci/config" >> $GITHUB_ENV
        echo "OCI_CLI_PROFILE=DEFAULT" >> $GITHUB_ENV

        # Set Terraform Provider Variables (using content for the provider)
        echo "TF_VAR_tenancy_ocid=${{ inputs.oci_tenancy_ocid }}" >> $GITHUB_ENV
        echo "TF_VAR_user_ocid=${{ inputs.oci_user_ocid }}" >> $GITHUB_ENV
        echo "TF_VAR_fingerprint=${{ inputs.oci_fingerprint }}" >> $GITHUB_ENV
        echo "TF_VAR_region=${{ inputs.oci_region }}" >> $GITHUB_ENV

        # Pass key content to Provider (as we configured in variables.tf)
        echo "TF_VAR_private_key<<EOF" >> $GITHUB_ENV
        echo "${{ inputs.oci_private_key }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        if [ -n "${{ inputs.ssh_public_key }}" ]; then
          echo "TF_VAR_ssh_public_key=${{ inputs.ssh_public_key }}" >> $GITHUB_ENV
        fi
