name: Setup Rust
description: Sets up the Rust toolchain and caches dependencies

inputs:
  toolchain:
    description: Rust toolchain version
    default: stable

runs:
  using: composite
  steps:
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Cache Cargo Registry and Build
      uses: Swatinem/rust-cache@v2
