name: Set Terraform Environment
description: Determines the target environment and sets TF_VAR_FILE

inputs:
  environment:
    description: 'Manual environment input (Development/Production)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      run: |
        # Determine environment from input or branch
        TARGET_ENV="${{ inputs.environment }}"
        
        # If no input, fallback to branch logic
        if [[ -z "$TARGET_ENV" ]]; then
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TARGET_ENV="Production"
          else
            TARGET_ENV="Development"
          fi
        fi
        
        echo "Selected Environment: $TARGET_ENV"
        
        if [[ "$TARGET_ENV" == "Production" ]]; then
          echo "TF_VAR_FILE=environments/prod/prod.tfvars" >> $GITHUB_ENV
        else
          echo "TF_VAR_FILE=environments/dev/dev.tfvars" >> $GITHUB_ENV
        fi
